# 端口号
server:
  port: 80

# 数据库配置信息
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/ssm_test

# 前缀改为tbl_
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      # 使用数据库自增策略
      id-type: auto
  # 设置mq的运行日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

